exclude: 'build'

default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
        args: ['--branch=master']
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: end-of-file-fixer

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
    -   id: insert-license
        files: \.py$
        args:
        - --license-filepath
        - docs/license_header.txt
    -   id: insert-license
        files: \.js$|\.jsx$
        args:
        - --license-filepath
        - docs/license_header.txt
        - --comment-style
        - /*| *| */
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.2.1
    hooks:
    -   id: pyupgrade
        args: ['--py36-plus']

-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    -   id: isort
        additional_dependencies: [toml]
        exclude: ^website

-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
    -   id: prettier
        files: \.[jt]sx?$

-   repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
    -   id: stylelint
        args: [--fix]
        additional_dependencies:
            - stylelint@13.11.0
            - stylelint-config-standard@20.0.0

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.21.0
    hooks:
    -   id: eslint
        args: [--fix --silent]
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
            - eslint@7.21.0
            - eslint-config-react-app
