extends:
    - stylelint-config-recommended
    - stylelint-config-standard
rules:
    indentation: 4
    font-family-no-missing-generic-family-keyword:
    - true
    - ignoreFontFamilies: [OpenSansSemiBold, OpenSansLight, OpenSansRegular]
