[tool.isort]
# This is required to make sorting same as fbcode as all absolute imports
# are considered third party there
known_third_party = [
    "transformers", "yoyo", "boto3", "bottle", "aiohttp", "pyjwt", "jwt", "cheroot",
    "numpy", "sqlalchemy", "pymysql", "requests", "six", "SQLAlchemy", "sagemaker",
    "torch", "tqdm", "werkzeug", "cryptography", "mephisto", "omegaconf", "hydra",
    "mmf", "PIL", "ts", "captum", "dateutil", "uuid", "pandas", "enum", "botocore",
    "sacrebleu", "sentencepiece"
]
skip_glob = "**/build/**,frontends/**"
combine_as_imports = true
force_grid_wrap = false
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true
lines_after_imports = 2

[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | website
)/
'''
